[phases.setup]
nixPkgs = ['...', 'gradle']

[phases.build]
cmds = ['gradle clean build -x test']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=test -jar build/libs/check-0.0.1-SNAPSHOT.jar'
